import { StyleSheet } from 'react-native';
import { getColorsByTheme, addOpacity } from '../../../styles/colors';

export const getStyles = (isDarkMode) => {
  const COLORS = getColorsByTheme(isDarkMode);
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.background,
    },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 40,
    gap: 14,
  },
  card: {
      backgroundColor: COLORS.cardBg,
      borderRadius: 14,
      padding: 16,
      borderWidth: 1,
      borderColor: COLORS.borderLight,
      gap: 12,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  cardDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textSecondary,
  },
  selectButton: {
    height: 46,
    borderRadius: 12,
      backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  selectButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '600',
  },
    importButton: {
      height: 46,
      borderRadius: 12,
      backgroundColor: COLORS.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
  importButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  fileName: {
    color: COLORS.textSecondary,
    fontSize: 13,
  },
    loadingWrapper: {
      backgroundColor: isDarkMode ? addOpacity(COLORS.primary, 6) : COLORS.secondaryLighter,
      borderRadius: 12,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
  loadingText: {
    color: COLORS.textSecondary,
    fontSize: 13,
  },
    importLoadingCard: {
      backgroundColor: isDarkMode ? addOpacity(COLORS.primary, 6) : COLORS.secondaryLighter,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDarkMode ? COLORS.border : COLORS.secondaryBorder,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 6,
    },
  importLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  importLoadingTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
    importLoadingStep: {
      fontSize: 13,
      color: COLORS.primaryDark,
      fontWeight: '600',
      minHeight: 18,
    },
  importLoadingHint: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
    reviewSection: {
      backgroundColor: COLORS.cardBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: COLORS.borderLight,
      padding: 12,
    },
  reviewHeader: {
    marginBottom: 10,
  },
  reviewSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  reviewListScroll: {
    maxHeight: 420,
  },
  reviewListContent: {
    gap: 10,
    paddingBottom: 4,
  },
    transactionCard: {
      backgroundColor: COLORS.cardBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      padding: 14,
      gap: 10,
    },
  pendingActionGroup: {
    gap: 8,
  },
    pendingActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 8,
      backgroundColor: COLORS.error,
      borderRadius: 8,
    },
  pendingActionButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },
  transactionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  transactionHeaderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  transactionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  transactionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
    statusBadgeCompleta: {
      backgroundColor: addOpacity(COLORS.success, 12),
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    statusBadgeTextCompleta: {
      fontSize: 11,
      fontWeight: '700',
      color: COLORS.success,
    },
    statusBadgePendente: {
      backgroundColor: addOpacity(COLORS.warning, 12),
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    statusBadgeTextPendente: {
      fontSize: 11,
      fontWeight: '700',
      color: COLORS.warning,
    },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  switchLabel: {
    fontSize: 13,
    color: COLORS.textSecondary,
  },
    noteText: {
      fontSize: 12,
      color: COLORS.warning,
      backgroundColor: addOpacity(COLORS.warning, 12),
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 8,
    },
    collapsedSummary: {
      fontSize: 13,
      color: COLORS.textSecondary,
      backgroundColor: isDarkMode ? COLORS.backgroundLight : COLORS.secondaryLighter,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    input: {
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 10,
      backgroundColor: COLORS.backgroundLight,
      paddingHorizontal: 12,
      height: 44,
      fontSize: 14,
      color: COLORS.textPrimary,
    },
  twoColumns: {
    flexDirection: 'row',
    gap: 10,
  },
  halfInput: {
    flex: 1,
  },
    pickerContainer: {
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 10,
      overflow: 'hidden',
      backgroundColor: COLORS.backgroundLight,
    },
    picker: {
      height: 50,
      color: COLORS.textPrimary,
    },
  saveButton: {
    marginTop: 6,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  saveButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
  },
    validationErrorCard: {
      backgroundColor: addOpacity(COLORS.error, 10),
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.error,
      padding: 14,
      gap: 10,
    },
  validationErrorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
    validationErrorTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: COLORS.error,
    },
    validationErrorMessage: {
      fontSize: 13,
      color: COLORS.error,
      lineHeight: 18,
    },
    refreshPendingButton: {
      marginTop: 4,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: COLORS.error,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
  refreshPendingButtonText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '700',
  },
  validationActionButtons: {
    marginTop: 12,
    gap: 8,
  },
    validationActionLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: COLORS.error,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
  buttonGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
    validationActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: COLORS.error,
      borderRadius: 8,
      justifyContent: 'center',
    },
  validationActionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.white,
  },
    modalOverlay: {
      flex: 1,
      backgroundColor: COLORS.overlay,
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: COLORS.backgroundLight,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      maxHeight: '80%',
      paddingTop: 20,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.borderLight,
    },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  modalBody: {
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  modalInfo: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
    fontStyle: 'italic',
  },
    modalInput: {
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
      color: COLORS.textPrimary,
      marginBottom: 20,
    },
  typeButtonsContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
    typeToggleButton: {
      flex: 1,
      flexDirection: 'row',
      gap: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderWidth: 2,
      borderColor: COLORS.border,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
  typeToggleButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
  },
  typeToggleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  typeToggleButtonTextActive: {
    color: COLORS.white,
  },
    modalCloseButton: {
      backgroundColor: isDarkMode ? COLORS.background : addOpacity(COLORS.secondaryLighter, 50),
      paddingVertical: 14,
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 10,
    },
  modalCloseButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.primary,
    textAlign: 'center',
  },
  modalSaveButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  modalSaveButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.white,
    textAlign: 'center',
  },
});

};

export const styles = getStyles(false);
