import { StyleSheet } from 'react-native';
import { getColorsByTheme } from '../../../styles/colors';
import { FOOTER_HEIGHT } from '../../../componentes/BotoesAcaoFixo';

export const getStyles = (isDarkMode) => {
  const COLORS = getColorsByTheme(isDarkMode);
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 20,
  },
  screen: {
    flex: 1,
  },
  scroll: {
    flex: 1,
    backgroundColor: COLORS.background,
    marginBottom: FOOTER_HEIGHT,
  },
  contentContainer: {
    paddingBottom: 20,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 25,
  },
  label: {
    fontSize: 16,
    color: COLORS.textPrimary,
    marginBottom: 10,
    fontWeight: '500',
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  currencySymbol: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    marginRight: 8,
  },
  amountInput: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  dateInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    gap: 10,
  },
  dateInput: {
    flex: 1,
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  typeButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  typeButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  typeButtonIncome: {
    backgroundColor: COLORS.background,
  },
  typeButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  typeButtonText: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  typeButtonTextActive: {
    color: COLORS.white,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginBottom: 15,
    backgroundColor: COLORS.background,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  categoryButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
    gap: 8,
  },
  categoryButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  categoryButtonText: {
    fontSize: 14,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  categoryButtonTextActive: {
    color: COLORS.white,
  },
  addCategoryButton: {
    borderColor: COLORS.primary,
    borderStyle: 'dashed',
    backgroundColor: isDarkMode ? (COLORS.primary + '15') : (COLORS.primaryLight + '10'),
  },
  addCategoryButtonText: {
    color: COLORS.primary,
    fontWeight: '600',
  },
  recurringRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 10,
  },
  marginTop0: {
    marginTop: 0,
  },
  recurringText: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  frequencyButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  frequencyButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  frequencyButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  frequencyButtonText: {
    fontSize: 14,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  frequencyButtonTextActive: {
    color: COLORS.white,
  },
  installmentButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 10,
  },
  installmentButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  installmentButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  installmentButtonText: {
    fontSize: 14,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  installmentButtonTextActive: {
    color: COLORS.white,
  },
  customInstallmentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
  },
  customInstallmentInput: {
    fontSize: 14,
    color: COLORS.textPrimary,
    fontWeight: '500',
    minWidth: 35,
    textAlign: 'center',
  },
  customInstallmentInputActive: {
    color: COLORS.white,
  },
  installmentValueContainer: {
    backgroundColor: isDarkMode ? (COLORS.primary + '20') : COLORS.primaryLighter,
    borderRadius: 12,
    padding: 14,
    marginTop: 10,
    marginBottom: 8,
  },
  installmentValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  installmentValueText: {
    fontSize: 15,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  installmentValueHighlight: {
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: '700',
  },
  warningContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  warningText: {
    fontSize: 12,
    color: COLORS.warning,
    fontWeight: '500',
  },
  installmentInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    paddingHorizontal: 4,
  },
  installmentInfoText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontStyle: 'italic',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginLeft: 4,
  },
  errorText: {
    fontSize: 12,
    color: COLORS.error,
    marginLeft: 4,
  },
  pickerLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginTop: 8,
    marginBottom: 8,
  },
  pickerContainer: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
  },
  picker: {
    height: 50,
    color: COLORS.textPrimary,
  },
  institutionTypeButtons: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  institutionTypeButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  institutionTypeButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  institutionTypeButtonText: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  institutionTypeButtonTextActive: {
    color: COLORS.white,
  },
  institutionChipContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: COLORS.background,
  },
  institutionChipWrapper: {
    flex: 1,
    marginRight: 8,
  },
  institutionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderRadius: 20,
    paddingVertical: 6,
    paddingLeft: 6,
    paddingRight: 12,
    alignSelf: 'flex-start',
    gap: 8,
  },
  chipIconContainer: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  chipLogoImage: {
    width: 28,
    height: 28,
    borderRadius: 8,
    objectFit: 'cover',
  },
  chipIconText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  chipText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  chipRemoveButton: {
    marginLeft: 4,
  },
  institutionPlaceholderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  institutionPlaceholderText: {
    fontSize: 15,
    color: COLORS.textTertiary,
  },
  institutionSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: COLORS.background,
  },
  institutionIcons: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  institutionIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  institutionIconText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: 'bold',
  },
  institutionLogoImage: {
    width: 36,
    height: 36,
  },
  institutionName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  institutionPlaceholder: {
    fontSize: 16,
    color: COLORS.textTertiary,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    marginHorizontal: 20,
    marginVertical: 30,
    paddingVertical: 16,
    borderRadius: 15,
    gap: 10,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  saveButtonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Estilos para seção de IA/Sugestões
  aiSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  aiSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: 12,
  },
  aiButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  aiButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDarkMode ? COLORS.primaryLighter : COLORS.secondaryLighter,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.primaryLight,
    gap: 8,
  },
  aiButtonText: {
    fontSize: 16,
    color: COLORS.primaryLight,
    fontWeight: '600',
  },
  processingCard: {
    marginTop: 15,
    backgroundColor: COLORS.background,
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  processingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 10,
  },
  loadingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.primaryLight,
  },
  processingText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  processingSubtext: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  suggestionCard: {
    marginTop: 15,
    backgroundColor: isDarkMode ? COLORS.primaryLighter : COLORS.secondaryLighter,
    padding: 18,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.primaryLight,
  },
  suggestionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 8,
  },
  suggestionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.primaryLight,
  },
  suggestionContent: {
    marginBottom: 15,
  },
  suggestionRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  suggestionLabel: {
    fontSize: 14,
    color: COLORS.textSecondary,
    width: 90,
    fontWeight: '500',
  },
  suggestionValue: {
    fontSize: 14,
    color: COLORS.textPrimary,
    flex: 1,
    fontWeight: '600',
  },
  suggestionButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  suggestionButtonReject: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  suggestionButtonRejectText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontWeight: '600',
  },
  suggestionButtonAccept: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    gap: 6,
  },
  suggestionButtonAcceptText: {
    fontSize: 14,
    color: COLORS.white,
    fontWeight: '600',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: COLORS.backgroundLight,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    minHeight: 300,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: COLORS.border,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  modalContent: {
    marginBottom: 24,
  },
  modalSuggestionRow: {
    marginBottom: 16,
  },
  modalSuggestionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textTertiary,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  modalSuggestionValue: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.textPrimary,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  modalButtonCancel: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonCancelText: {
    color: COLORS.textSecondary,
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtonConfirm: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  modalButtonConfirmText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  }
  });
};

export const styles = getStyles(false);
