import { StyleSheet } from 'react-native';
import COLORS from '../../../styles/colors';
import { FOOTER_HEIGHT } from '../../../componentes/BotoesAcaoFixo';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFF',
    paddingTop: 20,
  },
  screen: {
    flex: 1,
  },
  scroll: {
    flex: 1,
    backgroundColor: '#FFF',
    marginBottom: FOOTER_HEIGHT,
  },
  contentContainer: {
    paddingBottom: 20,
  },
  container: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 25,
  },
  label: {
    fontSize: 16,
    color: '#333',
    marginBottom: 10,
    fontWeight: '500',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: '#333',
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  currencySymbol: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginRight: 8,
  },
  amountInput: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  dateInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    gap: 10,
  },
  dateInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  typeButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  typeButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  typeButtonIncome: {
    backgroundColor: '#FFF',
  },
  typeButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  typeButtonText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  typeButtonTextActive: {
    color: '#FFF',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginBottom: 15,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  categoryButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    backgroundColor: '#FFF',
    gap: 8,
  },
  categoryButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  categoryButtonText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  categoryButtonTextActive: {
    color: '#FFF',
  },
  addCategoryButton: {
    borderColor: COLORS.primary,
    borderStyle: 'dashed',
    backgroundColor: COLORS.primaryLight + '10',
  },
  addCategoryButtonText: {
    color: COLORS.primary,
    fontWeight: '600',
  },
  recurringRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 10,
  },
  marginTop0: {
    marginTop: 0,
  },
  recurringText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  frequencyButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  frequencyButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  frequencyButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  frequencyButtonText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  frequencyButtonTextActive: {
    color: '#FFF',
  },
  installmentButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 10,
  },
  installmentButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  installmentButtonActive: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primaryLight,
  },
  installmentButtonText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  installmentButtonTextActive: {
    color: '#FFF',
  },
  customInstallmentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
  },
  customInstallmentInput: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
    minWidth: 35,
    textAlign: 'center',
  },
  customInstallmentInputActive: {
    color: '#FFF',
  },
  installmentValueContainer: {
    backgroundColor: COLORS.primaryLighter,
    borderRadius: 12,
    padding: 14,
    marginTop: 10,
    marginBottom: 8,
  },
  installmentValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  installmentValueText: {
    fontSize: 15,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  installmentValueHighlight: {
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: '700',
  },
  warningContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  warningText: {
    fontSize: 12,
    color: COLORS.warning,
    fontWeight: '500',
  },
  installmentInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    paddingHorizontal: 4,
  },
  installmentInfoText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontStyle: 'italic',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginLeft: 4,
  },
  errorText: {
    fontSize: 12,
    color: COLORS.error,
    marginLeft: 4,
  },
  pickerLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginTop: 8,
    marginBottom: 8,
  },
  pickerContainer: {
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
  },
  picker: {
    height: 50,
  },
  institutionTypeButtons: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  institutionTypeButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  institutionTypeButtonActive: {
    backgroundColor: '#5BA3FF',
    borderColor: '#5BA3FF',
  },
  institutionTypeButtonText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  institutionTypeButtonTextActive: {
    color: '#FFF',
  },
  institutionChipContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#FFF',
  },
  institutionChipWrapper: {
    flex: 1,
    marginRight: 8,
  },
  institutionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderRadius: 20,
    paddingVertical: 6,
    paddingLeft: 6,
    paddingRight: 12,
    alignSelf: 'flex-start',
    gap: 8,
  },
  chipIconContainer: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  chipLogoImage: {
    width: 28,
    height: 28,
    borderRadius: 8,
    objectFit: 'cover',
  },
  chipIconText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  chipText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  chipRemoveButton: {
    marginLeft: 4,
  },
  institutionPlaceholderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  institutionPlaceholderText: {
    fontSize: 15,
    color: '#999',
  },
  institutionSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  institutionIcons: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  institutionIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  institutionIconText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  institutionLogoImage: {
    width: 36,
    height: 36,
  },
  institutionName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  institutionPlaceholder: {
    fontSize: 16,
    color: '#999',
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5BA3FF',
    marginHorizontal: 20,
    marginVertical: 30,
    paddingVertical: 16,
    borderRadius: 15,
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  saveButtonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Estilos para seção de IA/Sugestões
  aiSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  aiSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
  },
  aiButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  aiButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0F7FF',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#5BA3FF',
    gap: 8,
  },
  aiButtonText: {
    fontSize: 16,
    color: '#5BA3FF',
    fontWeight: '600',
  },
  processingCard: {
    marginTop: 15,
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  processingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 10,
  },
  loadingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#5BA3FF',
  },
  processingText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  processingSubtext: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  suggestionCard: {
    marginTop: 15,
    backgroundColor: '#F0F7FF',
    padding: 18,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#5BA3FF',
  },
  suggestionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 8,
  },
  suggestionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#5BA3FF',
  },
  suggestionContent: {
    marginBottom: 15,
  },
  suggestionRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  suggestionLabel: {
    fontSize: 14,
    color: '#666',
    width: 90,
    fontWeight: '500',
  },
  suggestionValue: {
    fontSize: 14,
    color: '#333',
    flex: 1,
    fontWeight: '600',
  },
  suggestionButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  suggestionButtonReject: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  suggestionButtonRejectText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  suggestionButtonAccept: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5BA3FF',
    gap: 6,
  },
  suggestionButtonAcceptText: {
    fontSize: 14,
    color: '#FFF',
    fontWeight: '600',
  },
});
